### ISSUE TITLE
Improve loading performance

### ISSUE THREAD

**Issue by sojusnik** [gowong/tabtrekker#59]
Hi!

In comparison to the [Google Art Firefox Add-on](https://addons.mozilla.org/de/firefox/addon/art-project/) TabTrekker seems to load the pictures slower, as shown [here](https://mega.nz/#!2sQwEbCB!KOmUzkEhpw3J6HQgZhxV_F5p2q9MFCjfBihHw_RPru8) (Google Art) and [here](https://mega.nz/#!j0ZTnCCT!saDDb4seEif-HJ97nVK3agHFfHQc5fpkLq0Cq97Si7M) (TabTrekker). Is there a way to load the pictures faster?

Best wishes!

**Comment by gowong** [comment]
The images will load slower the first time that you get a new location each day. That's because TabTrekker is fetching the information about the location and the list of images (the other addon you linked only loads one image at a time). After that, TabTrekker will download each image locally so that they load quicker. 

Yes, it could be improved by downloading the images in the background first and then only showing the images for the new location when all of the images are downloaded. It requires a decent amount of effort so I'm not sure if it's worth it since the loading delay only exists for the first load each day.

**Comment by gowong** [comment]
Some of the fixes for this have been released
